esphome:
  name: esphome-web-f7xdfx
  friendly_name: KapU-D1mini32
  includes:
    - uart_read_line_sensor.h

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE 
  baud_rate: 0 

# Enable Home Assistant API
api:
  encryption:
    key: "" #cseréld sajátra

ota:
  - platform: esphome
    password: "" #cseréld sajátra

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-F7XDfX"
    password: "" #cseréld sajátra

captive_portal:
    
web_server:
  local: true
  port: 80

uart:
  id: uart_bus
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600

text_sensor:
  - platform: custom
    lambda: |-
      auto my_custom_sensor = new UartReadLineSensor(id(uart_bus));
      App.register_component(my_custom_sensor);
      return {my_custom_sensor};
    text_sensors:
      id: "uart_readline"

switch:
  - platform: gpio
    pin: GPIO2
    name: "Kapu-statusz-esp"
    id: "kapustatuszesp"
  - platform: restart
    name: "Restart"

button:
  - platform: template
    name: "Nyitás"
    on_press:
      - uart.write: "FULL OPEN\r"
  - platform: template
    name: "Zárás"
    on_press:
      - uart.write: "FULL CLOSE\r"
  - platform: template
    name: "Stop"
    on_press:
      - uart.write: "STOP\r"
  - platform: template
    name: "Kiskapu"
    on_press:
      - uart.write: "PED OPEN\r"

sensor:
  - platform: template
    name: "UART_text"
    update_interval: 5s
    filters:
      delta: 1.0
    lambda: |-
      static std::string last_state = "";
      if (id(uart_readline).state != last_state) {
        last_state = id(uart_readline).state;
        if (id(uart_readline).state.find("Opening") != std::string::npos) {
          if (!id(kapustatuszesp).state) {
            id(kapustatuszesp).turn_on();
          }
          return 1;
        } else if  (id(uart_readline).state.find("Opened") != std::string::npos) {
          return 2;
        } else if  (id(uart_readline).state.find("Closing") != std::string::npos) {
          return 3;
        } else if  (id(uart_readline).state.find("Closed") != std::string::npos) {
          if (id(kapustatuszesp).state) {
            id(kapustatuszesp).turn_off();
          }
          return 4;
        } else if  (id(uart_readline).state.find("Stopped") != std::string::npos) {
          return 5;
        } else if  (id(uart_readline).state.find("PedOpening") != std::string::npos) {
          if (!id(kapustatuszesp).state) {
            id(kapustatuszesp).turn_on();
          }
          return 6;
        } else if  (id(uart_readline).state.find("PedOpened") != std::string::npos) {
          return 7;
        } else {
          return 0;
        }
      } else {
        return {};
      }
